# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkd" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "1709959201f965add5287ea877c4c6801ab51c2eab33e347dd1933b318a882e2"
      url "https://github.com/cunhazera/mkd/releases/download/v#{version}/mkd_Darwin_x86_64.tar.gz",
        verified: "github.com/cunhazera/mkd"
    end
    on_arm do
      sha256 "bd22c66f7ba2f80381fd6652470b57ae546f66d7c2af11ecf25d7acc0fd934fe"
      url "https://github.com/cunhazera/mkd/releases/download/v#{version}/mkd_Darwin_arm64.tar.gz",
        verified: "github.com/cunhazera/mkd"
    end
  end

  on_linux do
    on_intel do
      sha256 "a2cdf8e1eb29125cc770aac540ac0a296c98abd9e7e1d27b7e424743c22fce8c"
      url "https://github.com/cunhazera/mkd/releases/download/v#{version}/mkd_Linux_x86_64.tar.gz",
        verified: "github.com/cunhazera/mkd"
    end
    on_arm do
      sha256 "035dc4c73af68bb3e64d5917312d5a91b37df611e50eb4b07e462fd07c8757e5"
      url "https://github.com/cunhazera/mkd/releases/download/v#{version}/mkd_Linux_arm64.tar.gz",
        verified: "github.com/cunhazera/mkd"
    end
  end

  name "mkd"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mkd"]
    end
  end

  # No zap stanza required

end
