# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkd" do
  version "0.3.4"

  on_macos do
    on_intel do
      sha256 "abfaabe030c9969a4cd2fa4d4134b908b8ee7b5f7f6b0ff4c645b2d52ae82433"
      url "https://github.com/cunhazera/mkd/releases/download/v#{version}/mkd_Darwin_x86_64.tar.gz",
        verified: "github.com/cunhazera/mkd"
    end
    on_arm do
      sha256 "cd8ef7ef46e95d3ac847ec9ecd10a93d07ebcfe1826df3f1db319bb783b23bff"
      url "https://github.com/cunhazera/mkd/releases/download/v#{version}/mkd_Darwin_arm64.tar.gz",
        verified: "github.com/cunhazera/mkd"
    end
  end

  on_linux do
    on_intel do
      sha256 "e8e4a931dd3cf26be27abf52a9a10cf3d8fafdee684588c0d9199de0d2dc4aff"
      url "https://github.com/cunhazera/mkd/releases/download/v#{version}/mkd_Linux_x86_64.tar.gz",
        verified: "github.com/cunhazera/mkd"
    end
    on_arm do
      sha256 "a7cb6a70527b8143b24ed1f4a331349b8f97ae66e02ec2bf597ec7f2b07cf713"
      url "https://github.com/cunhazera/mkd/releases/download/v#{version}/mkd_Linux_arm64.tar.gz",
        verified: "github.com/cunhazera/mkd"
    end
  end

  name "mkd"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mkd"]
    end
  end

  # No zap stanza required

end
