# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkd" do
  version "0.3.5"

  on_macos do
    on_intel do
      sha256 "6d1aa3269194df1ca3837bc03030da01be599e572a3f0546912b4c26818eb891"
      url "https://github.com/cunhazera/mkd/releases/download/v#{version}/mkd_Darwin_x86_64.tar.gz",
        verified: "github.com/cunhazera/mkd"
    end
    on_arm do
      sha256 "ddd805e7e13f2a2932403a8c954cb1605ba94d8fcbd46e2809701271dc92152a"
      url "https://github.com/cunhazera/mkd/releases/download/v#{version}/mkd_Darwin_arm64.tar.gz",
        verified: "github.com/cunhazera/mkd"
    end
  end

  on_linux do
    on_intel do
      sha256 "09b99c7f170be46c69caca7ca225a821a94a430b7cb1f24b91e961ea9a096243"
      url "https://github.com/cunhazera/mkd/releases/download/v#{version}/mkd_Linux_x86_64.tar.gz",
        verified: "github.com/cunhazera/mkd"
    end
    on_arm do
      sha256 "b676c4c178daa2d6358f6aa65be8224569b426059f62bfe09d3dce768e31abd7"
      url "https://github.com/cunhazera/mkd/releases/download/v#{version}/mkd_Linux_arm64.tar.gz",
        verified: "github.com/cunhazera/mkd"
    end
  end

  name "mkd"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mkd"]
    end
  end

  # No zap stanza required

end
