# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkd < Formula
  desc "A terminal markdown viewer with syntax highlighting and search"
  homepage "https://github.com/cunhazera/mkd"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cunhazera/mkd/releases/download/v0.3.1/mkd_Darwin_x86_64.tar.gz"
      sha256 "c54fe341773decd21a81df57ac30aebe028dadd3b0fa7c5d5235cc35c158d2d9"

      define_method(:install) do
        bin.install "mkd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cunhazera/mkd/releases/download/v0.3.1/mkd_Darwin_arm64.tar.gz"
      sha256 "0c5c1862fa6b3cf4ddb436a0d52fca775532d689b27e963d99d54f5b1990d320"

      define_method(:install) do
        bin.install "mkd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cunhazera/mkd/releases/download/v0.3.1/mkd_Linux_x86_64.tar.gz"
      sha256 "891fe8b799b768c3e3717e7935a905177608d77ec79235cc561d493b8f5b74cf"
      define_method(:install) do
        bin.install "mkd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cunhazera/mkd/releases/download/v0.3.1/mkd_Linux_arm64.tar.gz"
      sha256 "9e1407c335c2651c18d50de3257a158c874883062dba355bdf5574cdc82d8766"
      define_method(:install) do
        bin.install "mkd"
      end
    end
  end

  test do
    system "#{bin}/mkd", "--version"
  end
end
