# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkd < Formula
  desc "A terminal markdown viewer with syntax highlighting and search"
  homepage "https://github.com/cunhazera/mkd"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cunhazera/mkd/releases/download/v0.3.0/mkd_Darwin_x86_64.tar.gz"
      sha256 "891b96af01289b257c236c8e549aa3cee1328864ca35d3f56d8847078c954748"

      define_method(:install) do
        bin.install "mkd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cunhazera/mkd/releases/download/v0.3.0/mkd_Darwin_arm64.tar.gz"
      sha256 "53e1b33142a4acd1bca5ed5f4fa78662f700a6d03db80e71538de1caf1dc2d3b"

      define_method(:install) do
        bin.install "mkd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cunhazera/mkd/releases/download/v0.3.0/mkd_Linux_x86_64.tar.gz"
      sha256 "1e79a8237281dfb8946bda3e0dba74217962caa5155d1a3c417986566a6fdd37"
      define_method(:install) do
        bin.install "mkd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cunhazera/mkd/releases/download/v0.3.0/mkd_Linux_arm64.tar.gz"
      sha256 "1d86e491e723e5f6c11e1ec0702306a4026102aa62fe3d2595eede457ed01968"
      define_method(:install) do
        bin.install "mkd"
      end
    end
  end

  test do
    system "#{bin}/mkd", "--version"
  end
end
