# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkd < Formula
  desc "A terminal markdown viewer with syntax highlighting and search"
  homepage "https://github.com/cunhazera/mkd"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cunhazera/mkd/releases/download/v0.3.2/mkd_Darwin_x86_64.tar.gz"
      sha256 "7c50d64e8e385a720834603e862f31dccd518e2b4a5d027e1a97c8474f71231b"

      define_method(:install) do
        bin.install "mkd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cunhazera/mkd/releases/download/v0.3.2/mkd_Darwin_arm64.tar.gz"
      sha256 "7a8e8a99d98c8171fd1cb9ebe0462c89b1d1f56f6dddad6e96514673fcec1af5"

      define_method(:install) do
        bin.install "mkd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cunhazera/mkd/releases/download/v0.3.2/mkd_Linux_x86_64.tar.gz"
      sha256 "e9712f74f01d00a80367a10c1a09b6e28f7c7bb807d282cd35dffc5dd0a991b2"
      define_method(:install) do
        bin.install "mkd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cunhazera/mkd/releases/download/v0.3.2/mkd_Linux_arm64.tar.gz"
      sha256 "033324f69f7f4f5728bc9db9f6c39662a4b48b639371f6cc8df4f60655bdda6b"
      define_method(:install) do
        bin.install "mkd"
      end
    end
  end

  test do
    system "#{bin}/mkd", "--version"
  end
end
